name: Java CI

on:
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'v*.*.*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'v*.*.*'

permissions:
  contents: read
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          #distribution: 'adopt'
          #architecture: x64

      - name: Build with Maven
        run: mvn package -DskipTests=true

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is the default env for the password