# Separate workflow to release a new version of the Encrypt-api 
# This will be triggered by push a new tag looking like "encrypt-api-v*", where '*' is any text
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'encrypt-api-v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  deploy_to_mvn_central:
    name: Build Jars and deploy to Maven Central
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with: # running setup-java again overwrites the settings.xml
        java-version: 11
        distribution: 'zulu'
        cache: 'maven'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: OSSRH_USERNAME # env variable for username in deploy
        server-password: OSSRH_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
    - name: Publish to Apache Maven Central
      working-directory: ./encrypt-api # Run from the encrypt-api directory (instead of main -> which would be the parent-pom)
      run: mvn deploy -DskipTests=true -P deploy
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}